"""
Database configuration for AirIndex India.

Provides:
  - SQLAlchemy 2.0 DeclarativeBase with PostgreSQL naming conventions
  - Engine and session factory creation
  - FastAPI-compatible session dependency

Usage:
    from app.core.database import Base, get_engine, SessionLocal

The DATABASE_URL is read from the environment. For PostgreSQL:
    postgresql+psycopg://user:pass@host:5432/dbname
"""

from __future__ import annotations

import os
from collections.abc import Generator
from typing import Any

from sqlalchemy import MetaData, create_engine
from sqlalchemy.orm import DeclarativeBase, Session, sessionmaker

from typing import Optional

# ---------------------------------------------------------------------------
# Naming conventions — keeps constraint names consistent and predictable
# across all tables, which is critical for Alembic migrations.
# See: https://alembic.sqlalchemy.org/en/latest/naming.html
# ---------------------------------------------------------------------------

NAMING_CONVENTION: dict[str, str] = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Shared declarative base for all ORM models.

    Uses a custom MetaData with naming conventions so that autogenerated
    constraint names are predictable and Alembic can manage them reliably.
    """

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


# ---------------------------------------------------------------------------
# Engine and session helpers
# ---------------------------------------------------------------------------


def get_database_url() -> str:
    """Read DATABASE_URL from environment, falling back to a local default."""
    return os.environ.get(
        "DATABASE_URL",
        "postgresql+psycopg://airindex:change-me@localhost:5432/airindex",
    )


def get_engine(url: str | None = None, **kwargs: Any):
    """Create a SQLAlchemy engine.

    Args:
        url: Database URL. If None, reads from environment.
        **kwargs: Forwarded to ``create_engine`` (e.g. ``echo=True``).
    """
    if url is None:
        url = get_database_url()
    return create_engine(url, **kwargs)


def get_session_factory(engine=None) -> sessionmaker[Session]:
    """Create a sessionmaker bound to *engine*.

    Args:
        engine: SQLAlchemy engine. If None, a default engine is created.
    """
    if engine is None:
        engine = get_engine()
    return sessionmaker(bind=engine, autocommit=False, autoflush=False)


# Convenience alias — initialized via init_db() at app startup.
SessionLocal: Optional[sessionmaker[Session]] = None


def init_db(url: str | None = None) -> sessionmaker[Session]:
    """Initialize the module-level session factory.

    Safe to call multiple times (e.g. in tests); each call rebinds
    SessionLocal to a new factory bound to the given URL.
    """
    global SessionLocal
    SessionLocal = get_session_factory(get_engine(url))
    return SessionLocal


def get_db() -> Generator[Session, None, None]:
    """FastAPI dependency: yield a session and ensure it closes.

    Usage in FastAPI::

        @app.get("/items")
        def read_items(db: Session = Depends(get_db)):
            ...
    """
    if SessionLocal is None:
        raise RuntimeError(
            "SessionLocal is not initialized. Call get_session_factory() first."
        )
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
